# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-24 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0002_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Fashion & Style', 'FASHION & STYLE'), ('Cars & Property', 'CARS & PROPERTY'), ('Electronics & Mobiles', 'ELECTRONICS & MOBILES'), ('Home & Living', 'HOME & LIVING'), ('Others', 'Others')], default='Fashion & Style', max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-posted_time']},
        ),
    ]
