# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-24 13:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0005_auto_20181024_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
    ]
